config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV['PASSWORD_ADMIN'] && password == ENV['PASSWORD_ADMIN']
  end

  mount Sidekiq::Web => '/sidekiq'

  root 'items#index'

  get 'login' => 'authentication#login'
  post 'authenticate' => 'authentication#authenticate'
  get 'logout' => 'authentication#logout'

  resources :items, only: [:index, :new, :create] do
    collection do
      get :archive
    end

    member do
      post :return
      post :request_return
    end
  end
end

app/models/item.rb
class Item
  include Mongoid::Document
  include Mongoid::Timestamps
  include GlobalID::Identification

  field :description, type: String
  field :borrower_email, type: String
  field :returned_at, type: Time
  field :last_notification_at, type: Time
  field :last_return_request_at, type: Time
  field :agreed_to_terms, type: Boolean

  validates_presence_of :description, :borrower_email, :agreed_to_terms
  validates_acceptance_of :agreed_to_terms, accept: true
  validates :borrower_email, email: { strict_mode: true }

  scope :borrowed, -> { where(returned_at: nil) }
  scope :returned, -> { where(:returned_at.exists => true) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper

  protect_from_forgery with: :exception
  before_action :check_auth

  def check_auth
    if params[:password]
      login_with_password(params[:password])
    end
  end

  def login_with_password(password)
    if password == ENV['PASSWORD_ADMIN']
      session[:user] = 'admin'
      return true
    elsif password == ENV['PASSWORD_TERMINAL']
      session[:user] = 'terminal'
      return true
    end

    false
  end

  def check_user(*roles)
    return true if roles.include?(session[:user])

    redirect_to :root, notice: 'Please login first!'
    false
  end
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  def authenticate
    if login_with_password(params[:login][:password])
      flash[:notice] = 'Successfully logged in!'
    end

    redirect_to :root
  end

  def logout
    session[:user] = 'none'
    redirect_to :root, notice: 'Successfully logged out!'
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.borrowed.order_by(created_at: :desc).all
  end

  def new
    return unless check_user('terminal', 'admin')
    @item = Item.new
  end

  def create
    return unless check_user('terminal', 'admin')
    @item = Item.new(permitted_params[:item])
    if @item.save
      redirect_to items_path, notice: 'Successfully borrowed item!'
    else
      render 'new'
    end
  end

  def return
    return unless check_user('admin')
    Item.find(params[:id]).update!(returned_at: Time.now)
    redirect_to items_path, notice: 'Item successfully returned!'
  end

  def request_return
    return unless check_user('admin')
    @item = Item.find(params[:id])
    RequestMailer.request_email(@item).deliver_later!
    @item.update!(last_return_request_at: Time.now)
    redirect_to items_path, notice: 'Request sent!'
  end

  def archive
    return unless check_user('admin')
    @items = Item.returned.order_by(returned_at: :desc).all
  end

  protected

  def permitted_params
    params.permit(item: [:description, :borrower_email, :agreed_to_terms])
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def authenticate
    if params[:login][:password] == ENV['PASSWORD_ADMIN']
      session[:user] = 'admin'
      flash[:notice] = 'Successfully logged in as admin!'
    elsif params[:login][:password] == ENV['PASSWORD_TERMINAL']
      session[:user] = 'terminal'
      flash[:notice] = 'Successfully logged in as terminal!'
    end

    redirect_to :root
  end

  def logout
    session[:user] = 'none'
    redirect_to :root, notice: 'Successfully logged out!'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def admin?
    session[:user] == 'admin'
  end

  def terminal?
    session[:user] == 'terminal'
  end
end

app/views/authentication/login.html.slim
h2 Login

= form_tag authenticate_path do
  ul
    li
      = label :login, :password
      = password_field :login, :password
    li
      = submit_tag 'Login'

app/views/items/archive.html.slim
h2 Archive

table
  tr
    th Description
    th Borrower
    th Borrowed At
    th Returned At
  - @items.each do |item|
    tr
      td = item.description
      td = item.borrower_email
      td = item.created_at
      td = item.returned_at

app/views/items/index.html.slim
h2 List

table
  tr
    th Description
    th Borrower
    th Time
    - if admin?
      th Last Notification
      th Last Return Request
      th Actions

  - @items.each do |item|
    tr
      td = item.description
      td = item.borrower_email
      td = time_ago_in_words(item.created_at) + ' ago'
      - if admin?
        td = item.last_notification_at ? time_ago_in_words(item.last_notification_at) + ' ago' : ''
        td = item.last_return_request_at ? time_ago_in_words(item.last_return_request_at) + ' ago' : ''
        td
          = link_to 'Return', return_item_path(item), method: :post
          = link_to 'Request', request_return_item_path(item), method: :post

app/views/items/new.html.slim
h2 Borrow

= semantic_form_for @item do |f|
  ul
    = f.input :description, hint: 'Short description about the item.'
    = f.input :borrower_email, as: :email, label: 'Email', hint: 'The borrowers @zhdk email address.'
    = f.input :agreed_to_terms, as: :boolean, checked_value: true, unchecked_value: false, label: 'Agreed to Borrowing Terms', hint: 'You are fully responsible for the borrowed items and have to return them in the same condition as you have received them. The borrower (identified by the email address) is also responsible if the item is lost or damaged by a third party. We keep the right to demand fees for repairing or replacing the item in such circumstances.'
    = f.action :submit, label: 'Borrow'

app/views/layouts/application.html.slim
doctype html
html
  head
    title MiniLeihs
    meta name="mobile-web-app-capable" content="yes"
    meta name="apple-mobile-web-app-capable" content="yes"
    = favicon_link_tag 'logo.png', rel: 'apple-touch-icon', type: 'image/png'
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  body
    .nav
      h1 = ENV['SHOP_NAME']
      ul
        li = link_to 'List', items_path
        - if admin? || terminal?
          li = link_to 'Borrow', new_item_path
        - else
          li = link_to 'Login', login_path
        - if admin?
          li = link_to 'Archive', archive_items_path
          li = link_to 'Logout', logout_path
    - if flash[:notice]
      .notice = flash[:notice]
    = yield